version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: my_mysqldb
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - my_network

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: my_phpadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - my_network

    # Symfony apache project container
    www:
        build: ./docker/
        container_name: my_project
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
            - ./project:/var/www/project
        restart: always
        networks:
            - my_network

networks:
    my_network:

volumes:
    db-data: